name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 上传整个仓库根目录作为 Pages 工件
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # 部署到 Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
