name: Deploy to GitHub Pages

# 以 main 分支有变动时触发
on:
  push:
    branches: [ main ]

# 全局声明必须的权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ⚠️ 这里必须加上 environment，否则 deploy-pages 找不到 pages 环境
    environment:
      name: github-pages

    steps:
      # 1. 签出源码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. （可选）如果你有构建步骤，就放这里
      # - name: Build site
      #   run: npm ci && npm run build

      # 3. 上传整个静态站点根目录作 artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .      # 如果你的网站输出在其它目录，比如 ./dist，就改成那个路径

      # 4. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
